import Head from 'next/head'
import css from '../styles/agenda.module.css'
import { useForm } from "react-hook-form";
import { useState, useRef } from "react";

export default function Home() {
  const [result, setResult] = useState()
  const { register, handleSubmit, formState: { errors } } = useForm()
  const onSubmit = data =>{
  setResult(data.item)
  }

  return (
    <div className={css.wrapper}>
      <Head>
        <title>To-Do-List</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

        <section className={css.container}>
            <h1 className={css.h1}>To-do list</h1>
            <div>
              <form onSubmit={handleSubmit(onSubmit)}>
                    <div className={css.input}>
                        <label>Digite seu item:</label>
                        <input className={css.textInput} {...register("item")}  />
                    </div>
                    <input type="submit" value='Adicionar'/>
                    <div className={css.input}>
                        <label className={css.label}>Apagar todos riscados</label>
                    </div>
                    <ul id='lista'>
                      <li>
                        {result}
                      </li>
                    </ul>
                </form>
            </div>
        </section>
    </div>
  )
}
